#ifndef UTILS_H_
#define UTILS_H_

class Utils
{
public: __thiscall Utils::Utils(void)
public: __thiscall Utils::~Utils(void)
public: class Utils & __thiscall Utils::operator=(class Utils const &)
public: static bool __cdecl Utils::CatBlanks(char * const,int,int)
public: static bool __cdecl Utils::CatString(char * const,char const *,int)
public: static bool __cdecl Utils::ConvertDayHourMinuteSecondToTime(long,long,long,long,long *)
public: static bool __cdecl Utils::ConvertTimeToDayString(long,long,long,char *,long *)
public: static bool __cdecl Utils::ConvertTimeToHourString(long,long,long,char *,long *)
public: static bool __cdecl Utils::ConvertTimeToMinuteString(long,long,long,char *,long *)
public: static bool __cdecl Utils::ConvertTimeToSecondString(long,long,long,char *,long *)
public: static bool __cdecl Utils::GetTimeString(long,long,char * const)
public: static bool __cdecl Utils::IsAnyCoalitionExist(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static bool __cdecl Utils::IsCampaignStageCompleted(int)
public: static bool __cdecl Utils::IsHumanExist(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static bool __cdecl Utils::PrintSystemTime(char const *)
public: static bool __cdecl Utils::checkUnitCategory(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >,class _bstr_t)
public: static bool __cdecl Utils::getForceUseMissionOptions(void)
public: static bool __cdecl Utils::getSetGlobal(void)
public: static bool __cdecl Utils::isMissionReadOnly(void)
public: static class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> > __cdecl Utils::GetAlliesCoalition(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> > __cdecl Utils::GetEnemyCoalition(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> > __cdecl Utils::getCurrentMissionOptions(void)
public: static class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> > __cdecl Utils::getMissionOptions(int)
public: static class _com_ptr_t<class _com_IIID<struct MSXML::IXMLDOMDocument,&struct __s_GUID _GUID_2933bf81_7b36_11d2_b20e_00c04f983e60> > __cdecl Utils::OpenXMLDoc(class _bstr_t)
public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Utils::createMeasureString(float)
public: static float __cdecl Utils::convertCentigradeToCentigradeOrFahrenheit(float)
public: static float __cdecl Utils::convertKmsOrNMilesToKms(float)
public: static float __cdecl Utils::convertKmsToKmsOrNMiles(float)
public: static float __cdecl Utils::convertMetersOrFeetToMeters(float)
public: static float __cdecl Utils::convertMetersToMetersOrFeet(float)
public: static float __cdecl Utils::convertMetersToUserUnits(float)
public: static float __cdecl Utils::revertAngle(float)
public: static int __cdecl Utils::getUnitPictureID(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >,class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static long __cdecl Utils::GetLongFromString(char const *)
public: static long __cdecl Utils::convertCategory(long,bool)
public: static long __cdecl Utils::convertTask(long,bool)
public: static void __cdecl Utils::AddStringWithDivision(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,int,int,bool)
public: static void __cdecl Utils::CatBlanks_T(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,int)
public: static void __cdecl Utils::SetProperReadOnlyStateForControls(class std::vector<class UI::Element *,class std::allocator<class UI::Element *> > const &)
public: static void __cdecl Utils::copyPlayerOptions(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >,class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::focusOnEditBox(class Control *)
public: static void __cdecl Utils::loadSetGlobal(void)
public: static void __cdecl Utils::overrideMissionOptions(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::reinitializeScenes(void)
public: static void __cdecl Utils::saveSetGlobal(void)
public: static void __cdecl Utils::selectAndFocusOnEditBox(class Control *)
public: static void __cdecl Utils::setCountryToStaticWithIcon(class StaticWithIcon *,class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::setForceUseMissionOptions(bool)
public: static void __cdecl Utils::setReadOnlyForControls(class Control * *,class Control *,bool)
public: static void __cdecl Utils::setReadOnlyForControls(class Control *,int *,int,bool)
public: static void __cdecl Utils::setSetGlobal(bool)
public: static void __cdecl Utils::setToDefaultMissionOptions(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >,class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::trySetPilotFromLogBookCamp(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::trySetPilotFromLogBookMiss(class _com_ptr_t<class _com_IIID<struct IUnknown,&struct __s_GUID _GUID_00000000_0000_0000_c000_000000000046> >)
public: static void __cdecl Utils::windowSizeChangedMessage(void)
private: static int __cdecl Utils::QuantityOfLeadingZeroes(long,long)
}		/// namespace Utils

#endif

