/**
 * This file is part of Flight Dream, an Iran territory space flight simulator
 * project.
 *
 * This program is property intellectual. You can't copy or distribute nor this
 * file neither any other files of project without express permission of owner
 * of this project. All sources, files, informations, documentations, and even
 * special hardwares are proprietary.
 *
 *            Copyright (c) 2015-2016 by Vahid Heidari (DeltaCode).
 *                           All rights reserved.
 */

#ifndef EGALEDYNAMIC_H_
#define EGALEDYNAMIC_H_

public: __thiscall EagleDynamics::Common::Activator::Activator(class EagleDynamics::Common::Activator const &)
public: __thiscall EagleDynamics::Common::Activator::Activator(void)
public: __thiscall EagleDynamics::Common::AsyncLogFile::AsyncLogFile(class EagleDynamics::Common::AsyncLogFile const &)
public: __thiscall EagleDynamics::Common::AsyncLogFile::AsyncLogFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)
public: __thiscall EagleDynamics::Common::Bufferizer::Bufferizer(class EagleDynamics::Common::Bufferizer const &)
public: __thiscall EagleDynamics::Common::Bufferizer::Bufferizer(void const *,unsigned int)
public: __thiscall EagleDynamics::Common::Bufferizer::Bufferizer(void)
public: __thiscall EagleDynamics::Common::Cloneable::Cloneable(class EagleDynamics::Common::Cloneable const &)
public: __thiscall EagleDynamics::Common::Cloneable::Cloneable(void)
public: __thiscall EagleDynamics::Common::CommonBufferizer::CommonBufferizer(class EagleDynamics::Common::CommonBufferizer const &)
public: __thiscall EagleDynamics::Common::CommonBufferizer::CommonBufferizer(void)
protected: __thiscall EagleDynamics::Common::CommonSerializer::CommonSerializer(struct IStorage *,struct IStream *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: __thiscall EagleDynamics::Common::CommonSerializer::CommonSerializer(class EagleDynamics::Common::CommonSerializer const &)
public: __thiscall EagleDynamics::Common::CommonSerializer::CommonSerializer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::CommonSerializer::CommonSerializer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: __thiscall EagleDynamics::Common::CommonSerializer::CommonSerializer(void)
public: __thiscall EagleDynamics::Common::Customer::Customer(class EagleDynamics::Common::Customer const &)
public: __thiscall EagleDynamics::Common::Customer::Customer(class EagleDynamics::Common::Factory *)
public: __thiscall EagleDynamics::Common::Customer::Customer(void)
public: __thiscall EagleDynamics::Common::Event::Event(bool,enum EagleDynamics::Common::Event::Light)
public: __thiscall EagleDynamics::Common::Factory::Factory(class EagleDynamics::Common::Factory const &)
public: __thiscall EagleDynamics::Common::Factory::Factory(void)
public: __thiscall EagleDynamics::Common::FactoryManager::FactoryManager(class EagleDynamics::Common::FactoryManager const &)
public: __thiscall EagleDynamics::Common::FactoryManager::FactoryManager(void)
public: __thiscall EagleDynamics::Common::IManager::IManager(class EagleDynamics::Common::IManager const &)
public: __thiscall EagleDynamics::Common::IManager::IManager(void)
public: __thiscall EagleDynamics::Common::IReader::IReader(class EagleDynamics::Common::IReader const &)
public: __thiscall EagleDynamics::Common::IReader::IReader(void)
public: __thiscall EagleDynamics::Common::Identifiable::Identifiable(class EagleDynamics::Common::Identifiable const &)
public: __thiscall EagleDynamics::Common::Identifiable::Identifiable(void)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(struct _GUID const &)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(class EagleDynamics::Common::Identifier const &)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct _GUID const &)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(char const *)
public: __thiscall EagleDynamics::Common::Identifier::Identifier(void)
public: __thiscall EagleDynamics::Common::Localizer::Localizer(class EagleDynamics::Common::Localizer const &)
public: __thiscall EagleDynamics::Common::Localizer::Localizer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::Lockable::Lockable(class EagleDynamics::Common::Lockable const &)
public: __thiscall EagleDynamics::Common::Lockable::Lockable(void)
public: __thiscall EagleDynamics::Common::Manager::Manager(class EagleDynamics::Common::Manager const &)
public: __thiscall EagleDynamics::Common::Manager::Manager(void)
public: __thiscall EagleDynamics::Common::NamedEvent::NamedEvent(char const *)
public: __thiscall EagleDynamics::Common::NamedEvent::NamedEvent(char const *,bool,enum EagleDynamics::Common::NamedEvent::Light)
public: __thiscall EagleDynamics::Common::ObjectLock::ObjectLock(class EagleDynamics::Common::Lockable &)
public: __thiscall EagleDynamics::Common::ObjectLock::ObjectLock(class EagleDynamics::Common::Lockable *)
public: __thiscall EagleDynamics::Common::Parallelizer::Parallelizer(class EagleDynamics::Common::Parallelizer const &)
public: __thiscall EagleDynamics::Common::Parallelizer::Parallelizer(void)
public: __thiscall EagleDynamics::Common::Persistable::Persistable(class EagleDynamics::Common::Persistable const &)
public: __thiscall EagleDynamics::Common::Persistable::Persistable(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::Persistable::Persistable(class EagleDynamics::Common::Persistor *)
public: __thiscall EagleDynamics::Common::Persistable::Persistable(class EagleDynamics::Common::Persistor *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::Persistable::Persistable(void)
public: __thiscall EagleDynamics::Common::Persistor::Persistor(class EagleDynamics::Common::Persistor const &)
public: __thiscall EagleDynamics::Common::Persistor::Persistor(void)
public: __thiscall EagleDynamics::Common::PersistorsManager::PersistorsManager(class EagleDynamics::Common::PersistorsManager const &)
public: __thiscall EagleDynamics::Common::PersistorsManager::PersistorsManager(void)
public: __thiscall EagleDynamics::Common::Process::Process(class EagleDynamics::Common::Process const &)
public: __thiscall EagleDynamics::Common::Process::Process(void)
public: __thiscall EagleDynamics::Common::ProcessLocker::ProcessLocker(class EagleDynamics::Common::ProcessLocker const &)
public: __thiscall EagleDynamics::Common::ProcessLocker::ProcessLocker(void)
public: __thiscall EagleDynamics::Common::Profiler::Profiler(class EagleDynamics::Common::Profiler const &)
public: __thiscall EagleDynamics::Common::Profiler::Profiler(unsigned long,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned long)
public: __thiscall EagleDynamics::Common::ProfilersManager::ProfilersManager(class EagleDynamics::Common::ProfilersManager const &)
public: __thiscall EagleDynamics::Common::ProfilersManager::ProfilersManager(void)
public: __thiscall EagleDynamics::Common::RandomTimeKeeper::RandomTimeKeeper(class EagleDynamics::Common::RandomTimeKeeper const &)
public: __thiscall EagleDynamics::Common::RandomTimeKeeper::RandomTimeKeeper(void)
public: __thiscall EagleDynamics::Common::Record::Record(struct EagleDynamics::Common::Record const &)
public: __thiscall EagleDynamics::Common::Record::Record(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::Record::Record(void)
public: __thiscall EagleDynamics::Common::Registrator::Registrator(void (__cdecl*)(class EagleDynamics::Common::FactoryManager * *),class EagleDynamics::Common::Factory *)
public: __thiscall EagleDynamics::Common::Serializable::Serializable(class EagleDynamics::Common::Serializable const &)
public: __thiscall EagleDynamics::Common::Serializable::Serializable(void)
public: __thiscall EagleDynamics::Common::Serializer::Serializer(class EagleDynamics::Common::Serializer const &)
public: __thiscall EagleDynamics::Common::Serializer::Serializer(void)
protected: __thiscall EagleDynamics::Common::StorageSerializer::StorageSerializer(struct IStorage *,struct IStream *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: __thiscall EagleDynamics::Common::StorageSerializer::StorageSerializer(class EagleDynamics::Common::StorageSerializer const &)
public: __thiscall EagleDynamics::Common::StorageSerializer::StorageSerializer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: __thiscall EagleDynamics::Common::StorageSerializer::StorageSerializer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: __thiscall EagleDynamics::Common::StorageSerializer::StorageSerializer(void)
public: __thiscall EagleDynamics::Common::StreamSerializer::StreamSerializer(class EagleDynamics::Common::StreamSerializer const &)
public: __thiscall EagleDynamics::Common::StreamSerializer::StreamSerializer(void)
public: __thiscall EagleDynamics::Common::Thread::Thread(class EagleDynamics::Common::Thread const &)
public: __thiscall EagleDynamics::Common::Thread::Thread(bool)
public: __thiscall EagleDynamics::Common::ThreadLocker::ThreadLocker(class EagleDynamics::Common::ThreadLocker const &)
public: __thiscall EagleDynamics::Common::ThreadLocker::ThreadLocker(void)
public: __thiscall EagleDynamics::Common::TimeKeeper::TimeKeeper(class EagleDynamics::Common::TimeKeeper const &)
public: __thiscall EagleDynamics::Common::TimeKeeper::TimeKeeper(void)
public: virtual __thiscall EagleDynamics::Common::Activator::~Activator(void)
public: __thiscall EagleDynamics::Common::AsyncLogFile::~AsyncLogFile(void)
public: virtual __thiscall EagleDynamics::Common::Bufferizer::~Bufferizer(void)
public: virtual __thiscall EagleDynamics::Common::CommonBufferizer::~CommonBufferizer(void)
public: virtual __thiscall EagleDynamics::Common::CommonSerializer::~CommonSerializer(void)
public: virtual __thiscall EagleDynamics::Common::Customer::~Customer(void)
public: __thiscall EagleDynamics::Common::Event::~Event(void)
public: virtual __thiscall EagleDynamics::Common::Factory::~Factory(void)
public: virtual __thiscall EagleDynamics::Common::FactoryManager::~FactoryManager(void)
public: virtual __thiscall EagleDynamics::Common::IReader::~IReader(void)
public: virtual __thiscall EagleDynamics::Common::Identifiable::~Identifiable(void)
public: __thiscall EagleDynamics::Common::Identifier::~Identifier(void)
public: __thiscall EagleDynamics::Common::Localizer::~Localizer(void)
public: virtual __thiscall EagleDynamics::Common::Lockable::~Lockable(void)
public: __thiscall EagleDynamics::Common::NamedEvent::~NamedEvent(void)
public: __thiscall EagleDynamics::Common::ObjectLock::~ObjectLock(void)
public: virtual __thiscall EagleDynamics::Common::Parallelizer::~Parallelizer(void)
public: virtual __thiscall EagleDynamics::Common::Persistable::~Persistable(void)
public: virtual __thiscall EagleDynamics::Common::Persistor::~Persistor(void)
public: virtual __thiscall EagleDynamics::Common::PersistorsManager::~PersistorsManager(void)
public: virtual __thiscall EagleDynamics::Common::Process::~Process(void)
public: virtual __thiscall EagleDynamics::Common::ProcessLocker::~ProcessLocker(void)
public: __thiscall EagleDynamics::Common::Profiler::~Profiler(void)
public: virtual __thiscall EagleDynamics::Common::ProfilersManager::~ProfilersManager(void)
public: virtual __thiscall EagleDynamics::Common::RandomTimeKeeper::~RandomTimeKeeper(void)
public: __thiscall EagleDynamics::Common::Record::~Record(void)
public: virtual __thiscall EagleDynamics::Common::Serializable::~Serializable(void)
public: virtual __thiscall EagleDynamics::Common::Serializer::~Serializer(void)
public: virtual __thiscall EagleDynamics::Common::StorageSerializer::~StorageSerializer(void)
public: virtual __thiscall EagleDynamics::Common::StreamSerializer::~StreamSerializer(void)
public: virtual __thiscall EagleDynamics::Common::Thread::~Thread(void)
public: virtual __thiscall EagleDynamics::Common::ThreadLocker::~ThreadLocker(void)
public: virtual __thiscall EagleDynamics::Common::TimeKeeper::~TimeKeeper(void)
public: class EagleDynamics::Common::Activator & __thiscall EagleDynamics::Common::Activator::operator=(class EagleDynamics::Common::Activator const &)
public: class EagleDynamics::Common::AsyncLogFile & __thiscall EagleDynamics::Common::AsyncLogFile::operator=(class EagleDynamics::Common::AsyncLogFile const &)
public: class EagleDynamics::Common::Bufferizer & __thiscall EagleDynamics::Common::Bufferizer::operator=(class EagleDynamics::Common::Bufferizer const &)
public: class EagleDynamics::Common::Cloneable & __thiscall EagleDynamics::Common::Cloneable::operator=(class EagleDynamics::Common::Cloneable const &)
public: class EagleDynamics::Common::CommonBufferizer & __thiscall EagleDynamics::Common::CommonBufferizer::operator=(class EagleDynamics::Common::CommonBufferizer const &)
public: class EagleDynamics::Common::CommonSerializer & __thiscall EagleDynamics::Common::CommonSerializer::operator=(class EagleDynamics::Common::CommonSerializer const &)
public: class EagleDynamics::Common::Customer & __thiscall EagleDynamics::Common::Customer::operator=(class EagleDynamics::Common::Customer const &)
public: class EagleDynamics::Common::Event & __thiscall EagleDynamics::Common::Event::operator=(class EagleDynamics::Common::Event const &)
public: class EagleDynamics::Common::Factory & __thiscall EagleDynamics::Common::Factory::operator=(class EagleDynamics::Common::Factory const &)
public: class EagleDynamics::Common::FactoryManager & __thiscall EagleDynamics::Common::FactoryManager::operator=(class EagleDynamics::Common::FactoryManager const &)
public: class EagleDynamics::Common::IManager & __thiscall EagleDynamics::Common::IManager::operator=(class EagleDynamics::Common::IManager const &)
public: class EagleDynamics::Common::IReader & __thiscall EagleDynamics::Common::IReader::operator=(class EagleDynamics::Common::IReader const &)
public: class EagleDynamics::Common::Identifiable & __thiscall EagleDynamics::Common::Identifiable::operator=(class EagleDynamics::Common::Identifiable const &)
public: class EagleDynamics::Common::Identifier const & __thiscall EagleDynamics::Common::Identifier::operator=(class EagleDynamics::Common::Identifier const &)
public: class EagleDynamics::Common::Localizer & __thiscall EagleDynamics::Common::Localizer::operator=(class EagleDynamics::Common::Localizer const &)
public: class EagleDynamics::Common::Lockable & __thiscall EagleDynamics::Common::Lockable::operator=(class EagleDynamics::Common::Lockable const &)
public: class EagleDynamics::Common::Manager & __thiscall EagleDynamics::Common::Manager::operator=(class EagleDynamics::Common::Manager const &)
public: class EagleDynamics::Common::NamedEvent & __thiscall EagleDynamics::Common::NamedEvent::operator=(class EagleDynamics::Common::NamedEvent const &)
public: class EagleDynamics::Common::Parallelizer & __thiscall EagleDynamics::Common::Parallelizer::operator=(class EagleDynamics::Common::Parallelizer const &)
public: class EagleDynamics::Common::Persistable & __thiscall EagleDynamics::Common::Persistable::operator=(class EagleDynamics::Common::Persistable const &)
public: class EagleDynamics::Common::Persistor & __thiscall EagleDynamics::Common::Persistor::operator=(class EagleDynamics::Common::Persistor const &)
public: class EagleDynamics::Common::PersistorsManager & __thiscall EagleDynamics::Common::PersistorsManager::operator=(class EagleDynamics::Common::PersistorsManager const &)
public: class EagleDynamics::Common::Process & __thiscall EagleDynamics::Common::Process::operator=(class EagleDynamics::Common::Process const &)
public: class EagleDynamics::Common::ProcessLocker & __thiscall EagleDynamics::Common::ProcessLocker::operator=(class EagleDynamics::Common::ProcessLocker const &)
public: class EagleDynamics::Common::Profiler & __thiscall EagleDynamics::Common::Profiler::operator=(class EagleDynamics::Common::Profiler const &)
public: class EagleDynamics::Common::ProfilersManager & __thiscall EagleDynamics::Common::ProfilersManager::operator=(class EagleDynamics::Common::ProfilersManager const &)
public: class EagleDynamics::Common::RandomTimeKeeper & __thiscall EagleDynamics::Common::RandomTimeKeeper::operator=(class EagleDynamics::Common::RandomTimeKeeper const &)
public: struct EagleDynamics::Common::Record & __thiscall EagleDynamics::Common::Record::operator=(struct EagleDynamics::Common::Record const &)
public: class EagleDynamics::Common::Registrator & __thiscall EagleDynamics::Common::Registrator::operator=(class EagleDynamics::Common::Registrator const &)
public: class EagleDynamics::Common::Serializable & __thiscall EagleDynamics::Common::Serializable::operator=(class EagleDynamics::Common::Serializable const &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator=(class EagleDynamics::Common::Serializer const &)
public: class EagleDynamics::Common::StorageSerializer & __thiscall EagleDynamics::Common::StorageSerializer::operator=(class EagleDynamics::Common::StorageSerializer const &)
public: class EagleDynamics::Common::StreamSerializer & __thiscall EagleDynamics::Common::StreamSerializer::operator=(class EagleDynamics::Common::StreamSerializer const &)
public: class EagleDynamics::Common::Thread & __thiscall EagleDynamics::Common::Thread::operator=(class EagleDynamics::Common::Thread const &)
public: class EagleDynamics::Common::ThreadLocker & __thiscall EagleDynamics::Common::ThreadLocker::operator=(class EagleDynamics::Common::ThreadLocker const &)
public: class EagleDynamics::Common::TimeKeeper & __thiscall EagleDynamics::Common::TimeKeeper::operator=(class EagleDynamics::Common::TimeKeeper const &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(char &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(unsigned char &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(short &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(unsigned short &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(int &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(unsigned int &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(long &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(unsigned long &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(float &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(double &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(long double &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(class EagleDynamics::Common::Serializable &)
public: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::operator<<(bool &)
protected: virtual class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::StorageSerializer::operator<<(class EagleDynamics::Common::Serializable &)
public: bool __thiscall EagleDynamics::Common::Identifier::operator==(class EagleDynamics::Common::Identifier const &)const
public: bool __thiscall EagleDynamics::Common::Identifier::operator!=(class EagleDynamics::Common::Identifier const &)const
public: __thiscall EagleDynamics::Common::Bufferizer::operator bool(void)const
public: bool __thiscall EagleDynamics::Common::Identifier::operator<(class EagleDynamics::Common::Identifier const &)const
public: bool __thiscall EagleDynamics::Common::Record::operator<(struct EagleDynamics::Common::Record const &)const
const EagleDynamics::Common::Activator::`vftable'
const EagleDynamics::Common::AsyncLogFile::`vftable'
const EagleDynamics::Common::Bufferizer::`vftable'
const EagleDynamics::Common::Cloneable::`vftable'
const EagleDynamics::Common::CommonBufferizer::`vftable'
const EagleDynamics::Common::CommonSerializer::`vftable'
const EagleDynamics::Common::Customer::`vftable'
const EagleDynamics::Common::Factory::`vftable'
const EagleDynamics::Common::FactoryManager::`vftable'
const EagleDynamics::Common::IManager::`vftable'
const EagleDynamics::Common::IReader::`vftable'
const EagleDynamics::Common::Identifiable::`vftable'
const EagleDynamics::Common::Lockable::`vftable'
const EagleDynamics::Common::Manager::`vftable'
const EagleDynamics::Common::Parallelizer::`vftable'{for `EagleDynamics::Common::Thread'}
const EagleDynamics::Common::Parallelizer::`vftable'{for `EagleDynamics::Common::ThreadLocker'}
const EagleDynamics::Common::Persistable::`vftable'
const EagleDynamics::Common::Persistor::`vftable'
const EagleDynamics::Common::PersistorsManager::`vftable'
const EagleDynamics::Common::Process::`vftable'
const EagleDynamics::Common::ProcessLocker::`vftable'
const EagleDynamics::Common::ProfilersManager::`vftable'
const EagleDynamics::Common::RandomTimeKeeper::`vftable'
const EagleDynamics::Common::Serializable::`vftable'
const EagleDynamics::Common::Serializer::`vftable'
const EagleDynamics::Common::StorageSerializer::`vftable'
const EagleDynamics::Common::StreamSerializer::`vftable'
const EagleDynamics::Common::Thread::`vftable'
const EagleDynamics::Common::ThreadLocker::`vftable'
const EagleDynamics::Common::TimeKeeper::`vftable'
public: void __thiscall EagleDynamics::Common::AsyncLogFile::`default constructor closure'(void)
public: void __thiscall EagleDynamics::Common::Event::`default constructor closure'(void)
public: void __thiscall EagleDynamics::Common::Thread::`default constructor closure'(void)
public: void __thiscall EagleDynamics::Common::CommonBufferizer::Close(unsigned int &)
public: void __thiscall EagleDynamics::Common::StreamSerializer::Close(void)
public: static class EagleDynamics::Common::CommonBufferizer * __stdcall EagleDynamics::Common::CommonBufferizer::Create(void)
public: static class EagleDynamics::Common::StreamSerializer * __stdcall EagleDynamics::Common::StreamSerializer::Create(void)
public: virtual long __stdcall EagleDynamics::Common::Factory::CreateInstance(struct IUnknown *,struct _GUID const &,void * *)
public: virtual long __stdcall EagleDynamics::Common::Factory::CreateInstance(struct IUnknown *,class EagleDynamics::Common::Identifier const &,void * *)
public: virtual long __stdcall EagleDynamics::Common::FactoryManager::CreateInstance(struct IUnknown *,class EagleDynamics::Common::Identifier const &,void * *)
protected: enum EagleDynamics::Common::Persistor::Mode __thiscall EagleDynamics::Common::CommonSerializer::GetMode(void)
protected: enum EagleDynamics::Common::Persistor::Mode __thiscall EagleDynamics::Common::StorageSerializer::GetMode(void)
public: virtual long __stdcall EagleDynamics::Common::Factory::LockServer(int)
public: void __thiscall EagleDynamics::Common::CommonBufferizer::Open(enum EagleDynamics::Common::Persistor::Mode,void *,unsigned int)
public: void __thiscall EagleDynamics::Common::StreamSerializer::Open(enum EagleDynamics::Common::Persistor::Mode,struct IStream *)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::SetMode(enum EagleDynamics::Common::Persistor::Mode)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::SetMode(enum EagleDynamics::Common::Persistor::Mode)
protected: static void __stdcall EagleDynamics::Common::RandomTimeKeeper::TimerProc(unsigned int,unsigned int,unsigned long,unsigned long,unsigned long)
protected: static void __stdcall EagleDynamics::Common::TimeKeeper::TimerProc(unsigned int,unsigned int,unsigned long,unsigned long,unsigned long)
protected: virtual void __thiscall EagleDynamics::Common::Parallelizer::activate(void)
public: void __thiscall EagleDynamics::Common::Profiler::activate(void)
public: virtual void __thiscall EagleDynamics::Common::Thread::activate(void)
public: virtual void __thiscall EagleDynamics::Common::Factory::add(class EagleDynamics::Common::Identifier const &)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::add(class EagleDynamics::Common::Factory *)
public: virtual void __thiscall EagleDynamics::Common::PersistorsManager::add(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)
public: virtual void __thiscall EagleDynamics::Common::ProfilersManager::add(class EagleDynamics::Common::Profiler *)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::addFactory(class EagleDynamics::Common::Factory *)
protected: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::CommonBufferizer::allocate(class EagleDynamics::Common::Identifier const &)
protected: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::CommonSerializer::allocate(class EagleDynamics::Common::Identifier const &)
public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::Persistor::allocate(class EagleDynamics::Common::Identifier const &)
public: virtual void __thiscall EagleDynamics::Common::Persistor::allocate(class EagleDynamics::Common::Persistable *)
protected: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::StorageSerializer::allocate(class EagleDynamics::Common::Identifier const &)
protected: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::StreamSerializer::allocate(class EagleDynamics::Common::Identifier const &)
public: void __thiscall EagleDynamics::Common::Profiler::begin(unsigned long)
public: void __thiscall EagleDynamics::Common::Profiler::begin(void)
public: static unsigned long __stdcall EagleDynamics::Common::Activator::body(void *)
public: bool __thiscall EagleDynamics::Common::AsyncLogFile::clear(void)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::clear(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::clear(void)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::clear(void)
public: virtual void __thiscall EagleDynamics::Common::Persistor::clear(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::Persistor::clear(void)
public: virtual void __thiscall EagleDynamics::Common::PersistorsManager::clear(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::clear(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::clear(void)
public: virtual class EagleDynamics::Common::Identifiable * __thiscall EagleDynamics::Common::Factory::clone(class EagleDynamics::Common::Identifiable *)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::close(void)
public: virtual void __thiscall EagleDynamics::Common::Persistor::close(void)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::close(void)
public: virtual void __thiscall EagleDynamics::Common::Persistor::commit(void)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::commit(void)
public: void __cdecl EagleDynamics::Common::AsyncLogFile::compose(char const *,...)
protected: void __thiscall EagleDynamics::Common::Localizer::convert(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)
public: virtual void __thiscall EagleDynamics::Common::Factory::create(class EagleDynamics::Common::Identifier const &,class EagleDynamics::Common::Identifiable * *)
public: virtual class EagleDynamics::Common::Identifiable * __thiscall EagleDynamics::Common::FactoryManager::create(class EagleDynamics::Common::Identifier const &)
public: virtual class EagleDynamics::Common::IReader * __thiscall EagleDynamics::Common::Manager::createReader(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: void __thiscall EagleDynamics::Common::Profiler::deactivate(void)
protected: virtual void __thiscall EagleDynamics::Common::CommonBufferizer::deallocate(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
protected: virtual void __thiscall EagleDynamics::Common::CommonSerializer::deallocate(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::Persistor::deallocate(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::Persistor::deallocate(class EagleDynamics::Common::Persistable *)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::deallocate(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
protected: virtual void __thiscall EagleDynamics::Common::StreamSerializer::deallocate(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::defer(void)
public: virtual void __thiscall EagleDynamics::Common::Factory::destroy(class EagleDynamics::Common::Identifiable *)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::destroy(class EagleDynamics::Common::Identifiable *)
public: virtual void __thiscall EagleDynamics::Common::Manager::destroyReader(class EagleDynamics::Common::IReader *)
public: void __thiscall EagleDynamics::Common::Profiler::disable(unsigned long)
public: void __thiscall EagleDynamics::Common::Profiler::enable(unsigned long)
public: bool __thiscall EagleDynamics::Common::AsyncLogFile::enabled(void)const
public: void __thiscall EagleDynamics::Common::Profiler::end(unsigned long)
public: void __thiscall EagleDynamics::Common::Profiler::end(void)
protected: virtual void __thiscall EagleDynamics::Common::RandomTimeKeeper::engine(void)
protected: virtual void __thiscall EagleDynamics::Common::TimeKeeper::engine(void)
public: void __thiscall EagleDynamics::Common::AsyncLogFile::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,long)
protected: virtual void __thiscall EagleDynamics::Common::CommonBufferizer::fill(class EagleDynamics::Common::Persistable *)
protected: virtual void __thiscall EagleDynamics::Common::CommonSerializer::fill(class EagleDynamics::Common::Persistable *)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::fill(class EagleDynamics::Common::Persistable *)
protected: virtual void __thiscall EagleDynamics::Common::StreamSerializer::fill(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::Parallelizer::finalize(void)
public: bool __thiscall EagleDynamics::Common::AsyncLogFile::finish(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::Localizer::get(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: void __thiscall EagleDynamics::Common::Bufferizer::getBuffer(void const * &,unsigned int &)const
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall EagleDynamics::Common::Identifier::getClassName(void)const
public: class std::vector<class ATL::CComPtr<class EagleDynamics::Common::Factory>,class std::allocator<class ATL::CComPtr<class EagleDynamics::Common::Factory> > > const & __thiscall EagleDynamics::Common::FactoryManager::getFactories(void)const
public: virtual void __thiscall EagleDynamics::Common::Customer::getFactory(class EagleDynamics::Common::Factory * *)
public: virtual class EagleDynamics::Common::Factory * __thiscall EagleDynamics::Common::Customer::getFactory(void)const
public: struct _GUID const & __thiscall EagleDynamics::Common::Identifier::getGUID(void)const
public: void * __thiscall EagleDynamics::Common::Event::getHandle(void)
public: void * __thiscall EagleDynamics::Common::Thread::getHandle(void)
protected: unsigned int const & __thiscall EagleDynamics::Common::RandomTimeKeeper::getID(void)const
protected: unsigned int const & __thiscall EagleDynamics::Common::TimeKeeper::getID(void)const
public: virtual class EagleDynamics::Common::Identifier & __thiscall EagleDynamics::Common::Identifiable::getIdentifier(void)
public: virtual class EagleDynamics::Common::Identifier const & __thiscall EagleDynamics::Common::Identifiable::getIdentifier(void)const
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & __thiscall EagleDynamics::Common::Persistable::getName(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall EagleDynamics::Common::Persistable::getName(void)const
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & __thiscall EagleDynamics::Common::Persistor::getName(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall EagleDynamics::Common::Persistor::getName(void)const
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall EagleDynamics::Common::Profiler::getName(void)const
public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::PersistorsManager::getPath(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: double __thiscall EagleDynamics::Common::Profiler::getPercent(void)const
public: class EagleDynamics::Common::Persistor * __thiscall EagleDynamics::Common::Persistable::getPersistor(void)const
public: int __thiscall EagleDynamics::Common::Thread::getPriority(void)
public: double __thiscall EagleDynamics::Common::Profiler::getRate(void)const
void __cdecl getRegistry(class EagleDynamics::Common::FactoryManager * *)
public: unsigned long __thiscall EagleDynamics::Common::Profiler::getSize(void)const
class EagleDynamics::Common::AsyncLogFile & __cdecl EagleDynamics::Common::getSystemLog(void)
public: unsigned long __thiscall EagleDynamics::Common::Thread::getThreadId(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall EagleDynamics::Common::Localizer::getWithoutAdding(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
class EagleDynamics::Common::FactoryManager * EagleDynamics::Common::globalFactoryManager
class EagleDynamics::Common::IManager * EagleDynamics::Common::globalFileManager
class EagleDynamics::Common::AsyncLogFile * EagleDynamics::Common::globalLog
class EagleDynamics::Common::PersistorsManager * EagleDynamics::Common::globalPersistorsManager
class EagleDynamics::Common::ProfilersManager * EagleDynamics::Common::globalProfilersManager
public: virtual void __thiscall EagleDynamics::Common::Parallelizer::go(void)
public: void __thiscall EagleDynamics::Common::Event::green(void)
public: void __thiscall EagleDynamics::Common::NamedEvent::green(void)
public: virtual bool __thiscall EagleDynamics::Common::Lockable::interlock(void)
protected: unsigned long __thiscall EagleDynamics::Common::RandomTimeKeeper::intervalRand(unsigned long const &,unsigned long const &,bool)
public: bool __thiscall EagleDynamics::Common::Profiler::isEnabled(unsigned long)
public: virtual bool __thiscall EagleDynamics::Common::Bufferizer::isLoading(void)
public: virtual bool __thiscall EagleDynamics::Common::CommonSerializer::isLoading(void)
public: virtual bool __thiscall EagleDynamics::Common::Persistor::isLoading(void)
public: virtual bool __thiscall EagleDynamics::Common::StorageSerializer::isLoading(void)
public: virtual bool __thiscall EagleDynamics::Common::CommonSerializer::isOpened(void)
public: virtual bool __thiscall EagleDynamics::Common::Persistor::isOpened(void)
public: virtual bool __thiscall EagleDynamics::Common::StorageSerializer::isOpened(void)
public: virtual bool __thiscall EagleDynamics::Common::Factory::isPresent(class EagleDynamics::Common::Identifier const &)
public: virtual bool __thiscall EagleDynamics::Common::RandomTimeKeeper::kill(class EagleDynamics::Common::RandomTimeKeeper::TimeListener *)
public: virtual bool __thiscall EagleDynamics::Common::TimeKeeper::kill(class EagleDynamics::Common::TimeKeeper::TimeListener *)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::load(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::Persistable::load(void)
public: virtual void __thiscall EagleDynamics::Common::Persistor::load(class EagleDynamics::Common::Identifier const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class EagleDynamics::Common::Persistable * *)
public: virtual void __thiscall EagleDynamics::Common::Persistor::load(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::load(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::ProcessLocker::lock(void)
public: virtual void __thiscall EagleDynamics::Common::ThreadLocker::lock(void)
public: virtual bool __thiscall EagleDynamics::Common::Lockable::locked(void)
unsigned int __cdecl EagleDynamics::Common::mb2uni(unsigned char const * &)
int __cdecl EagleDynamics::Common::mbstrlen(unsigned char const *)
protected: virtual void __thiscall EagleDynamics::Common::RandomTimeKeeper::next(void)
public: virtual void __thiscall EagleDynamics::Common::AsyncLogFile::onTime(void)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::open(struct IUnknown *,enum EagleDynamics::Common::Persistor::Mode)
public: virtual bool __thiscall EagleDynamics::Common::CommonSerializer::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: virtual void __thiscall EagleDynamics::Common::Persistor::open(struct IUnknown *,enum EagleDynamics::Common::Persistor::Mode)
public: virtual bool __thiscall EagleDynamics::Common::Persistor::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::open(struct IUnknown *,enum EagleDynamics::Common::Persistor::Mode)
public: virtual bool __thiscall EagleDynamics::Common::StorageSerializer::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
protected: virtual void __thiscall EagleDynamics::Common::CommonSerializer::openStream(enum EagleDynamics::Common::Persistor::Mode,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct IStream * *)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::openStream(enum EagleDynamics::Common::Persistor::Mode,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct IStream * *)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::persist(class EagleDynamics::Common::Persistable * &)
public: virtual void __thiscall EagleDynamics::Common::Persistor::persist(class EagleDynamics::Common::Persistable * &)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::persist(class EagleDynamics::Common::Persistable * &)
public: void __thiscall EagleDynamics::Common::Profiler::process(void)
public: virtual void __thiscall EagleDynamics::Common::PersistorsManager::query(class EagleDynamics::Common::Persistor * *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum EagleDynamics::Common::Persistor::Mode)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::read(unsigned long &)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::read(class std::map<class EagleDynamics::Common::Identifier,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,unsigned long,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<unsigned long> >,struct std::less<class EagleDynamics::Common::Identifier>,class std::allocator<class std::map<class std::basic_string<ch
protected: void __thiscall EagleDynamics::Common::StorageSerializer::read(unsigned long &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::read(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::read(class std::map<struct EagleDynamics::Common::Record,unsigned long,struct std::less<struct EagleDynamics::Common::Record>,class std::allocator<unsigned long> > &)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::read(class EagleDynamics::Common::Persistable * &,bool)
public: void __thiscall EagleDynamics::Common::Event::red(void)
public: void __thiscall EagleDynamics::Common::NamedEvent::red(void)
class EagleDynamics::Common::FactoryManager * registry
public: virtual void __thiscall EagleDynamics::Common::Factory::remove(class EagleDynamics::Common::Identifier const &)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::remove(class EagleDynamics::Common::Factory *)
public: virtual void __thiscall EagleDynamics::Common::PersistorsManager::remove(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::ProfilersManager::remove(class EagleDynamics::Common::Profiler *)
public: virtual void __thiscall EagleDynamics::Common::FactoryManager::removeFactory(class EagleDynamics::Common::Factory *)
public: virtual class std::list<class EagleDynamics::Common::Identifier,class std::allocator<class EagleDynamics::Common::Identifier> > const & __thiscall EagleDynamics::Common::Factory::requestIdentifiers(void)const
public: void __thiscall EagleDynamics::Common::Thread::resume(void)
public: virtual void __thiscall EagleDynamics::Common::CommonSerializer::save(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::Persistable::save(void)
public: virtual void __thiscall EagleDynamics::Common::Persistor::save(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::StorageSerializer::save(class EagleDynamics::Common::Persistable *)
public: virtual void __thiscall EagleDynamics::Common::Bufferizer::serialize(void *,unsigned int)
protected: virtual void __thiscall EagleDynamics::Common::CommonBufferizer::serialize(void *,unsigned int)
protected: virtual void __thiscall EagleDynamics::Common::CommonSerializer::serialize(void *,unsigned int)
public: virtual void __thiscall RandomObject::serialize(class EagleDynamics::Common::Serializer &)
public: virtual void __thiscall EagleDynamics::Common::Serializable::serialize(class EagleDynamics::Common::Serializer &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(char &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(short &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(int &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(long &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(float &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(double &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(long double &)
public: class EagleDynamics::Common::Serializer & __thiscall EagleDynamics::Common::Serializer::serialize(bool &)
public: virtual void __thiscall EagleDynamics::Common::Serializer::serialize(void *,unsigned int)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::serialize(void *,unsigned int)
protected: virtual void __thiscall EagleDynamics::Common::StreamSerializer::serialize(void *,unsigned int)
public: void __thiscall EagleDynamics::Common::Profiler::set(unsigned long,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual bool __thiscall EagleDynamics::Common::RandomTimeKeeper::set(class EagleDynamics::Common::RandomTimeKeeper::TimeListener *,struct EagleDynamics::Common::TimerRand const &)
public: virtual bool __thiscall EagleDynamics::Common::TimeKeeper::set(class EagleDynamics::Common::TimeKeeper::TimeListener *,bool,unsigned int const &,unsigned int const &)
public: void __thiscall EagleDynamics::Common::Bufferizer::setBuffer(void const *,unsigned int)
public: void __thiscall EagleDynamics::Common::Identifier::setClassName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual void __thiscall EagleDynamics::Common::Customer::setFactory(class EagleDynamics::Common::Factory *)
public: void __thiscall EagleDynamics::Common::Identifier::setGUID(struct _GUID const &)
public: virtual void __thiscall EagleDynamics::Common::Identifiable::setIdentifier(class EagleDynamics::Common::Identifier const &)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::setName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: void __thiscall EagleDynamics::Common::Persistable::setName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::setName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: void __thiscall EagleDynamics::Common::Persistable::setPersistor(class EagleDynamics::Common::Persistor *)
public: void __thiscall EagleDynamics::Common::Thread::setPriority(int)
public: bool __thiscall EagleDynamics::Common::AsyncLogFile::start(void)
public: void __thiscall EagleDynamics::Common::Thread::suspend(void)
int __cdecl EagleDynamics::Common::uni2mb(unsigned char * &,unsigned int)
public: virtual void __thiscall EagleDynamics::Common::ProcessLocker::unlock(void)
public: virtual void __thiscall EagleDynamics::Common::ThreadLocker::unlock(void)
public: virtual void __thiscall EagleDynamics::Common::ProfilersManager::update(class EagleDynamics::Common::Profiler *)
public: bool __thiscall EagleDynamics::Common::Event::wait(unsigned long)
public: bool __thiscall EagleDynamics::Common::NamedEvent::wait(unsigned long)
public: void __cdecl EagleDynamics::Common::AsyncLogFile::write(char const *,...)
public: void __thiscall EagleDynamics::Common::AsyncLogFile::write(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::write(unsigned long &)
protected: void __thiscall EagleDynamics::Common::CommonSerializer::write(class std::map<class EagleDynamics::Common::Identifier,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,unsigned long,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<unsigned long> >,struct std::less<class EagleDynamics::Common::Identifier>,class std::allocator<class std::map<class std::basic_string<c
protected: void __thiscall EagleDynamics::Common::StorageSerializer::write(unsigned long &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::write(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)
protected: void __thiscall EagleDynamics::Common::StorageSerializer::write(class std::map<struct EagleDynamics::Common::Record,unsigned long,struct std::less<struct EagleDynamics::Common::Record>,class std::allocator<unsigned long> > &)
protected: virtual void __thiscall EagleDynamics::Common::StorageSerializer::write(class EagleDynamics::Common::Persistable *,bool)
public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl EagleDynamics::Common::Localizer::localize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl EagleDynamics::Common::Localizer::localizeWithoutAdding(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)

#endif

