#ifndef MULTICOLUMNLISTBOX_H_
#define MULTICOLUMNLISTBOX_H_

class MultiColumnListBox
{
public: __thiscall MultiColumnListBox::MultiColumnListBox(int,float,float,float,float)
public: __thiscall MultiColumnListBox::MultiColumnListBox(struct MultiColumnListBoxParameters const &)
public: virtual __thiscall MultiColumnListBox::~MultiColumnListBox(void)
public: bool __thiscall MultiColumnListBox::columnXSizeCalculated(void)
public: bool __thiscall MultiColumnListBox::getHasHorizontalLines(void)
public: bool __thiscall MultiColumnListBox::getHasVerticalLines(void)
public: bool __thiscall MultiColumnListBox::hasHeader(void)
public: bool __thiscall MultiColumnListBox::scrollBarNeed(void)
public: char const * __thiscall MultiColumnListBox::getItemCaption(int)
public: char const * __thiscall MultiColumnListBox::getItemCaption(int,int)const 
public: char const * __thiscall MultiColumnListBox::getString(int)
public: class MultiColumnListBox * __thiscall ComboBox::getList(void)const 
public: class MultiColumnListBox * __thiscall MenuButton::getList(void)
public: class Static * __thiscall MultiColumnListBox::getMarker1(void)const 
public: class Static * __thiscall MultiColumnListBox::getMarker2(void)const 
public: class Static * __thiscall MultiColumnListBox::item(int,int)
public: class TPoint<float> __thiscall MultiColumnListBox::findItem(char const *)
public: class TPoint<float> __thiscall MultiColumnListBox::getLastItemPressed(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall MultiColumnListBox::getDefaultItemSet(void)
public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall MultiColumnListBox::getHeaderSet(void)
public: float __thiscall MultiColumnListBox::getColumnWidth(int)
public: float __thiscall MultiColumnListBox::getRowHeight(int)
public: int __thiscall MultiColumnListBox::firstDataRow(void)
public: int __thiscall MultiColumnListBox::getColumnsNum(void)const 
public: int __thiscall MultiColumnListBox::getDefaultColumnDist(void)
public: int __thiscall MultiColumnListBox::getDefaultColumnWidth(void)
public: int __thiscall MultiColumnListBox::getDefaultColumnWidthFitType(void)
public: int __thiscall MultiColumnListBox::getDefaultLineColor(void)
public: int __thiscall MultiColumnListBox::getDefaultRowDist(void)
public: int __thiscall MultiColumnListBox::getDefaultRowHeight(void)
public: int __thiscall MultiColumnListBox::getFirstVisibleColumn(void)
public: int __thiscall MultiColumnListBox::getFirstVisibleRow(void)
public: int __thiscall MultiColumnListBox::getHasLines(void)
public: int __thiscall MultiColumnListBox::getHeaderDist(void)
public: int __thiscall MultiColumnListBox::getHeaderHeight(void)
public: int __thiscall MultiColumnListBox::getItemFace(int,int)
public: int __thiscall MultiColumnListBox::getLastFitType(void)
public: int __thiscall MultiColumnListBox::getLastVisibleColumn(void)
public: int __thiscall MultiColumnListBox::getLastVisibleRow(void)
public: int __thiscall MultiColumnListBox::getMarkerPosition(void)
public: int __thiscall MultiColumnListBox::getPagesNumber(void)
public: int __thiscall MultiColumnListBox::getRowsNum(void)const 
public: int __thiscall MultiColumnListBox::getSelectedColumn(void)const 
public: int __thiscall MultiColumnListBox::getSelectedRow(void)const 
public: struct Marker & __thiscall MultiColumnListBox::getMarker1Parameters(void)
public: struct Marker & __thiscall MultiColumnListBox::getMarker2Parameters(void)
public: virtual bool __thiscall MultiColumnListBox::addString(char const *,int)
public: virtual bool __thiscall MultiColumnListBox::canAcceptPoint(class TPoint<float> const &)const 
public: virtual bool __thiscall MultiColumnListBox::delField(int,int)
public: virtual bool __thiscall MultiColumnListBox::delRecord(int,int)
public: virtual bool __thiscall MultiColumnListBox::getSelection(int *,int *,bool)const 
public: virtual bool __thiscall MultiColumnListBox::getValue(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)const 
public: virtual bool __thiscall MultiColumnListBox::setSelection(int,int,bool)
public: virtual bool __thiscall MultiColumnListBox::setValue(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: virtual int __thiscall MultiColumnListBox::allFields(void)const 
public: virtual int __thiscall MultiColumnListBox::allRecords(void)const 
public: virtual int __thiscall MultiColumnListBox::newField(int,int)
public: virtual int __thiscall MultiColumnListBox::newRecord(int,int)
public: virtual void __thiscall MultiColumnListBox::clear(void)
public: virtual void __thiscall MultiColumnListBox::setCoordinates(float,float,float,float)
public: virtual void __thiscall MultiColumnListBox::setItemCaption(char const *,int,int)
public: virtual void __thiscall MultiColumnListBox::shift(float,float)
public: void __thiscall MultiColumnListBox::addColumns(int,int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
public: void __thiscall MultiColumnListBox::addRows(int,int,int)
public: void __thiscall MultiColumnListBox::arrange(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
public: void __thiscall MultiColumnListBox::arrange(struct MultiColumnListBoxParameters const &)
public: void __thiscall MultiColumnListBox::arrangeColumn(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)
public: void __thiscall MultiColumnListBox::arrangeHeader(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
public: void __thiscall MultiColumnListBox::arrangeItem(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int,int)
public: void __thiscall MultiColumnListBox::arrangeRow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)
public: void __thiscall MultiColumnListBox::calculateColumnFullSize(float *,int)
public: void __thiscall MultiColumnListBox::calculateColumnsFullSize(float *,float)
public: void __thiscall MultiColumnListBox::calculateFullXSize(float *,float)
public: void __thiscall MultiColumnListBox::calculateFullYSize(float *,float)
public: void __thiscall MultiColumnListBox::changeSelectedItem(int,int,int)
public: void __thiscall MultiColumnListBox::changeSelectedRow(int)
public: void __thiscall MultiColumnListBox::clearLines(void)
public: void __thiscall MultiColumnListBox::correctXRegion(void)
public: void __thiscall MultiColumnListBox::deleteColumns(int,int)
public: void __thiscall MultiColumnListBox::deleteRows(int,int,bool)
public: void __thiscall MultiColumnListBox::empty(void)
public: void __thiscall MultiColumnListBox::fitColumns(int)
public: void __thiscall MultiColumnListBox::freezeRows(int,int)
public: void __thiscall MultiColumnListBox::markerOff(void)
public: void __thiscall MultiColumnListBox::scroll(int,bool)
public: void __thiscall MultiColumnListBox::setColumnFullSize(int)
public: void __thiscall MultiColumnListBox::setColumnWidth(int,float)
public: void __thiscall MultiColumnListBox::setColumnsNum(int)
public: void __thiscall MultiColumnListBox::setCursorColor(unsigned int)
public: void __thiscall MultiColumnListBox::setDefaultColumnDist(int)
public: void __thiscall MultiColumnListBox::setDefaultColumnWidth(int)
public: void __thiscall MultiColumnListBox::setDefaultColumnWidthFitType(int)
public: void __thiscall MultiColumnListBox::setDefaultItemSet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
public: void __thiscall MultiColumnListBox::setDefaultLineColor(int)
public: void __thiscall MultiColumnListBox::setDefaultRowDist(int)
public: void __thiscall MultiColumnListBox::setDefaultRowHeight(int)
public: void __thiscall MultiColumnListBox::setFullXSize(float)
public: void __thiscall MultiColumnListBox::setFullYSize(float)
public: void __thiscall MultiColumnListBox::setHeader(bool)
public: void __thiscall MultiColumnListBox::setHeaderCaption(char const *,int)
public: void __thiscall MultiColumnListBox::setHeaderDist(int)
public: void __thiscall MultiColumnListBox::setHeaderHeight(int)
public: void __thiscall MultiColumnListBox::setHeaderSet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
public: void __thiscall MultiColumnListBox::setHorizontalLines(bool)
public: void __thiscall MultiColumnListBox::setItemCaption(char const *,int)
public: void __thiscall MultiColumnListBox::setItemFace(int,int,int)
public: void __thiscall MultiColumnListBox::setItemFontColor(int,int,int)
public: void __thiscall MultiColumnListBox::setItemOnOff(bool,int,int)
public: void __thiscall MultiColumnListBox::setItemType(int)
public: void __thiscall MultiColumnListBox::setKeepXRegion(bool)
public: void __thiscall MultiColumnListBox::setLines(bool)
public: void __thiscall MultiColumnListBox::setLines(void)
public: void __thiscall MultiColumnListBox::setMarker1(bool)
public: void __thiscall MultiColumnListBox::setMarker2(bool)
public: void __thiscall MultiColumnListBox::setMarkerPosition(int)
public: void __thiscall MultiColumnListBox::setRowFontColor(int,int)
public: void __thiscall MultiColumnListBox::setRowHeight(int,float)
public: void __thiscall MultiColumnListBox::setRowsNum(int)
public: void __thiscall MultiColumnListBox::setSelectedItem(char const *)
public: void __thiscall MultiColumnListBox::setSelectedItem(int,int)
public: void __thiscall MultiColumnListBox::setSelectedRow(int)
public: void __thiscall MultiColumnListBox::setTableSize(int,int)
public: void __thiscall MultiColumnListBox::setVerticalLines(bool)
public: void __thiscall MultiColumnListBox::undoFitColumns(void)
public: void __thiscall MultiColumnListBox::unfreezeRows(int,int)
Protected: int __thiscall MultiColumnListBox::xToColumn(float)
Protected: int __thiscall MultiColumnListBox::yToRow(float)
protected: float __thiscall MultiColumnListBox::calculateNextLTX(int,float)
protected: float __thiscall MultiColumnListBox::calculateNextLTY(int,float)
protected: float __thiscall MultiColumnListBox::calculateRBX(int,float)
protected: float __thiscall MultiColumnListBox::calculateRBY(int,float)
protected: float __thiscall MultiColumnListBox::getFirstColumnLTX(void)
protected: float __thiscall MultiColumnListBox::getFirstRowLTY(void)
protected: virtual class Control * __thiscall MultiColumnListBox::findChildByCoordAskChildren(class TPoint<float> const &,bool)
protected: virtual class Static * __thiscall MultiColumnListBox::CreateItem(int,int)
protected: virtual struct MSGTABLE const * __thiscall MultiColumnListBox::getMessageTable(void)const 
protected: virtual void __thiscall MultiColumnListBox::inflateChildren(void)
protected: virtual void __thiscall MultiColumnListBox::inflateSelf(void)
protected: virtual void __thiscall MultiColumnListBox::onCreate(void)
protected: virtual void __thiscall MultiColumnListBox::onLButtonDblclk(int,int,int)
protected: virtual void __thiscall MultiColumnListBox::onLButtonDown(int,int,int)
protected: virtual void __thiscall MultiColumnListBox::onMouseMove(int,int,int)
protected: virtual void __thiscall MultiColumnListBox::onMove(int,int)
protected: virtual void __thiscall MultiColumnListBox::onPaint(void)
protected: virtual void __thiscall MultiColumnListBox::onStyleChanging(bool,int)
protected: virtual void __thiscall MultiColumnListBox::paintChildren(void)
protected: void __thiscall MultiColumnListBox::adaptMarkerPosition(void)
protected: void __thiscall MultiColumnListBox::alignColumn(int,int)
protected: void __thiscall MultiColumnListBox::alignRow(int,int)
protected: void __thiscall MultiColumnListBox::alignStatic(int,int,int)
protected: void __thiscall MultiColumnListBox::alignTable(int)
protected: void __thiscall MultiColumnListBox::calculateCellsPositions(void)
protected: void __thiscall MultiColumnListBox::calculateLinesCoordinates(void)
protected: void __thiscall MultiColumnListBox::coordToItem(float,float,int *,int *)
protected: void __thiscall MultiColumnListBox::findVisibleItems(void)
protected: void __thiscall MultiColumnListBox::init(void)
protected: void __thiscall MultiColumnListBox::initializeCell(class Static *)
protected: void __thiscall MultiColumnListBox::onChar(char,int)
protected: void __thiscall MultiColumnListBox::onClose(void)
protected: void __thiscall MultiColumnListBox::onKeyDown(int,int)
protected: void __thiscall MultiColumnListBox::onKillFocus(class Control *)
protected: void __thiscall MultiColumnListBox::onMarkerClick(void)
protected: void __thiscall MultiColumnListBox::onMouseWheel(short,short,int,int)
protected: void __thiscall MultiColumnListBox::onSetFocus(class Control *)
protected: void __thiscall MultiColumnListBox::onSize(void)
protected: void __thiscall MultiColumnListBox::onVScroll(int,int,class Control *)
protected: void __thiscall MultiColumnListBox::setItemsCoordinates(void)
protected: void __thiscall MultiColumnListBox::setLinesNumber(int)
protected: void __thiscall MultiColumnListBox::setMarker1Position(void)
protected: void __thiscall MultiColumnListBox::setMarker2Position(void)
protected: void __thiscall MultiColumnListBox::setVisibleItems(void)
protected: void __thiscall MultiColumnListBox::tuneScrollBar(void)
private: void __thiscall MultiColumnListBox::setItemParams(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int,int)
private: void __thiscall MultiColumnListBox::thisArrange(struct MultiColumnListBoxParameters const &)
public: void __thiscall MultiColumnListBox::`vbase destructor'(void)
const MultiColumnListBox::`vbtable'{for `ControlWithScrollBar'}
const MultiColumnListBox::`vbtable'{for `UI::Chart'}
const MultiColumnListBox::`vftable'{for `Control'}
const MultiColumnListBox::`vftable'{for `UI::Chart'}
const MultiColumnListBox::`vftable'{for `UI::Element'}

protected: static struct MSGTABLE const MultiColumnListBox::messageTable
private: static struct MSGTABLE_ENTRY const * const MultiColumnListBox::messageEntries
};

#endif
