#ifndef LSYSTEM_H_
#define LSYSTEM_H_

class lSystem
{
public: struct gBox const & __thiscall nl::lRegion::getWorldBox(void)const 
public: __thiscall lSystem::lSystem(class lSystem const &)
public: __thiscall lSystem::lSystem(void)
public: virtual __thiscall lSystem::~lSystem(void)
public: class lSystem & __thiscall lSystem::operator=(class lSystem const &)
public: virtual bool __thiscall lSystem::IsOnAirfield(float,float)
public: virtual bool __thiscall lSystem::IsOnLake(float,float)
public: virtual bool __thiscall lSystem::IsOnRoad(float,float)
public: virtual bool __thiscall lSystem::WhereNearestGroundObject(class E3::Vector &,class E3::Vector &)
public: virtual bool __thiscall lSystem::isVisible(class E3::Vector &,class E3::Vector &)
public: virtual class E3::Vector * __thiscall lSystem::VectorGroundIntersection(class E3::Vector &,class E3::Vector &,float)
public: virtual class E3::Vector * __thiscall lSystem::VectorGroundIntersectionNormal(class E3::Vector &,class E3::Vector &,float,class E3::Vector &)
public: virtual class E3::Vector * __thiscall lSystem::groundIntersection(class E3::Vector &,class E3::Vector &)
public: virtual class lLandObject * __thiscall lSystem::GetObjectByIndex(unsigned int,bool)
public: virtual class lLandObject * __thiscall lSystem::NearestGroundObject(class E3::Vector &,class E3::Vector &,float,float)
public: virtual double __thiscall lSystem::GetXMax(void)
public: virtual double __thiscall lSystem::GetXMin(void)
public: virtual double __thiscall lSystem::GetZMax(void)
public: virtual double __thiscall lSystem::GetZMin(void)
public: virtual float __thiscall lSystem::Get_d2ObjectsCoeff(void)
public: virtual float __thiscall lSystem::heightBox(float,float)
public: virtual float __thiscall lSystem::heightSurface(float,float)
public: virtual float __thiscall lSystem::heightSurfaceNew(unsigned short &,float,float)
public: virtual int __thiscall lSystem::Envelope(class E3::Vector &,class E3::Vector &,class E3::Vector *,int)
public: virtual int __thiscall lSystem::GetObjects(float,float,float,float,class lLandObject * *,int,bool,unsigned int)
public: virtual int __thiscall lSystem::GetRectObjects(float,float,float,float,class lLandObject * *,int)
public: virtual int __thiscall lSystem::GetWObjects(class E3::Vector &,float,class cPointerTemplate<class MovingObject> *,int,unsigned int)
public: virtual int __thiscall lSystem::Init(void)
public: virtual int __thiscall lSystem::Restore(struct _iobuf *,short,bool)
public: virtual int __thiscall lSystem::Save(struct _iobuf *,bool)
public: virtual int __thiscall lSystem::surfaceTriangle(float,float,class E3::Vector &,class E3::Vector &,class E3::Vector &,class E3::Vector &,class E3::Vector &,unsigned int)
public: virtual int __thiscall lSystem::surfaceTrianglePlus(float,float,class E3::Vector &,class E3::Vector &,class E3::Vector &,class E3::Vector &,class E3::Vector &)
public: virtual unsigned char __thiscall lSystem::surfType(float,float)
public: virtual unsigned char __thiscall lSystem::surfTypePlus(float,float)
public: virtual void __thiscall lSystem::AddWObject(float,float,class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::ChangeRegion(float,float,class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::CleanScenes(void)
public: virtual void __thiscall lSystem::ClusterExplosion(class cPosition *,float,bool,bool,bool,bool,class cPointerTemplate<class MovingObject>,float,float,int,bool)
public: virtual void __thiscall lSystem::Draw(bool)
public: virtual void __thiscall lSystem::Draw2(float,float,float,float)
public: virtual void __thiscall lSystem::Explosion(class cPosition *,float,int,int,bool,bool,bool,bool,class cPointerTemplate<class MovingObject>,bool)
public: virtual void __thiscall lSystem::Explosion(class cPosition *,float,int,int,int,bool,int,bool,bool,bool,class cPointerTemplate<class MovingObject>,void *,int)
public: virtual void __thiscall lSystem::Finish(void)
public: virtual void __thiscall lSystem::InitOptions(void)
public: virtual void __thiscall lSystem::InitScenes(void)
public: virtual void __thiscall lSystem::NapalmExplosion(class cPosition *,float,float,bool,bool,bool,class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::NextTime(float)
public: virtual void __thiscall lSystem::ObjectExplosion(class lLandObject &,float,bool,bool,class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::OilExplosion(class cPosition *,float,bool,bool,bool,class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::RemoveWObject(class cPointerTemplate<class MovingObject>)
public: virtual void __thiscall lSystem::SetAirfieldLights(int,bool)
public: virtual void __thiscall lSystem::SetCameraType(unsigned char)
public: virtual void __thiscall lSystem::SetCommand(int)
public: virtual void __thiscall lSystem::Start(void)
public: virtual void __thiscall lSystem::Stop(void)
public: virtual void __thiscall lSystem::VolumeExplosion(class cPosition *,float,bool,bool,bool,class cPointerTemplate<class MovingObject>)
const lSystem::`vftable'
};

#endif

