#ifndef MATH_H_
#define MATH_H_

bool __cdecl SideBySide(class E3::Vector &,class E3::Vector &,float)
bool __fastcall BoxBoxIntersect(class Box const &,class Position3 const &,class Box const &,class Position3 const &)
bool __fastcall BoxBoxIntersect(class Position3 const &,class Vector3 const &,class Vector3 const &)
void __cdecl AddBoxToBox(struct cBox &,struct cBox &,bool)
void __cdecl AddVertexToBox(struct cBox &,class E3::Vector &,bool)
void __cdecl CalcRadius(struct cBox &)
void __cdecl Direction(class E3::Vector &,class E3::Vector &,class E3::Vector &)
void __cdecl Direction(class E3D::Vector &,class E3D::Vector &,class E3D::Vector &)
void __cdecl Slerp(class Quaternion *,class Quaternion *,class Quaternion *,float)
void __cdecl mult(class E3::Vector &,class cPosition &,class E3::Vector &)
void __cdecl mult(class E3D::Vector &,class dPosition &,class E3D::Vector &)
void __cdecl mult_move(class E3::Vector &,class cPosition &,class E3::Vector const &)
void __cdecl mult_move(class E3D::Vector &,class dPosition &,class E3D::Vector const &)
void __cdecl mult_transp(class E3::Vector &,class cPosition &,class E3::Vector &)
void __cdecl mult_transp(class E3D::Vector &,class dPosition &,class E3D::Vector &)
void __cdecl satm(float,float *,float *,float *)
void __fastcall ClipMesh(class std::vector<class Vector3,class std::allocator<class Vector3> > &,class std::vector<unsigned short,class std::allocator<unsigned short> > &,class Plane const &)
void __fastcall CrossP(struct D3DXVECTOR4 const *,struct D3DXVECTOR4 const *,struct D3DXVECTOR4 *)
void __fastcall DistortNormals(float *,unsigned long,unsigned long,float)
void __fastcall GenTorus(float,float,unsigned long,unsigned long,float *,unsigned short *,unsigned long *,unsigned long *)
void __fastcall GetFixedTransform(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall GetLocalX(void *,void *)
void __fastcall GetLocalY(void *,void *)
void __fastcall GetNormNorm(struct D3DXVECTOR3 const *,struct D3DXVECTOR3 const *,struct D3DXVECTOR3 const *,struct D3DXVECTOR4 *)
void __fastcall GetRollPitchRollTransform(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall GetTransformAlongX(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall GetTransformAlongY(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall GetTransformAlongZ(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall GetYawPitchTransform(struct D3DXVECTOR4 const *,struct D3DXMATRIX *,struct D3DXMATRIX *)
void __fastcall MapXZ2XY(struct D3DXVECTOR4 const *,struct D3DXMATRIX *)
void __fastcall Pitch(struct D3DXMATRIX &,float)
void __fastcall Quat2Matrix(struct D3DXVECTOR4 &,float,struct D3DXMATRIX &)
void __fastcall Roll(struct D3DXMATRIX &,float)
void __fastcall Yaw(struct D3DXMATRIX &,float)
void __fastcall rotate(void *,void *,float)
void __fastcall rotate2(void *,void *,float,float)
double __cdecl Bearing(class E3D::Vector &,class E3D::Vector &)
double __cdecl Distance(class E3D::Vector &,class E3D::Vector &)
double __cdecl Distance2(class E3D::Vector &,class E3D::Vector &)
double __cdecl Hor_Distance(class E3D::Vector &,class E3D::Vector &)
double __cdecl Hor_Distance2(class E3D::Vector &,class E3D::Vector &)
double __cdecl Pitch(class E3D::Vector &,class E3D::Vector &)
float __cdecl Air_Density(float)
float __cdecl Bearing(class E3::Vector &,class E3::Vector &)
float __cdecl Distance(class E3::Vector &,class E3::Vector &)
float __cdecl Distance2(class E3::Vector &,class E3::Vector &)
float __cdecl Hor_Distance(class E3::Vector &,class E3::Vector &)
float __cdecl Hor_Distance2(class E3::Vector &,class E3::Vector &)
float __cdecl Pitch(class E3::Vector &,class E3::Vector &)
float __cdecl Vel_of_Sound(float)
float __cdecl splah(int,float *,float *,float,int)
float __fastcall GetMyTime(void)
float __fastcall PointSegmentDistance(class Vector3 const &,class Vector3 const &,class Vector3 const &)
gD3DInvertMatrix44d
gD3DMultMatrix44Point3f
gD3DMultMatrix44d
int __cdecl fnMath(void)
int nMath

class Vector3 & __fastcall operator*=(class Vector3 &,class Matrix33 const &)
class Vector3 & __fastcall operator*=(class Vector3 &,class Position3 const &)
class Vector3 __cdecl IntersectPlanes(class Plane const &,class Plane const &,class Plane const &)
class Vector3 __fastcall operator*(class Vector3 const &,class Matrix33 const &)
class Vector3 __fastcall operator*(class Vector3 const &,class Position3 const &)

#endif

